In [127]:
import numpy as np


In [17]:
arr1 = np.array([[56,78],[44,54]], dtype=np.float)

C:\Users\Mikayel\AppData\Local\Temp/ipykernel_21292/3015246171.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr1 = np.array([[56,78],[44,54]], dtype=np.float)


In [13]:
arr1

array([[56, 78],
       [44, 54]])

In [14]:
arr1.shape

(2, 2)

In [15]:
arr1.ndim

2

In [24]:
arr2 = np.arange(4, 10, 2.2)

In [25]:
arr2

array([4. , 6.2, 8.4])

In [26]:
arr1 = np.arange(1, 20)

In [27]:
arr1.ndim

1

In [28]:
arr1.shape

(19,)

In [29]:
np.sqrt(np.std(arr1))

2.340347319320716

In [140]:
mx1 = np.array([[1, 2, 3, 4, 5, 6],[7, 8, 9, 10, 11, 12]])

In [141]:
mx2 = np.array([[13,14,15,16,17,18],[19,20 ,21, 22, 23, 24]])

In [142]:
mx2

array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [143]:
mx1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [144]:
mx_sum = mx1+mx2

In [145]:
mx_sum

array([[14, 16, 18, 20, 22, 24],
       [26, 28, 30, 32, 34, 36]])

In [146]:
mx_concat = np.concatenate((mx1, mx2))

In [147]:
mx_concat

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [148]:
mx_bigger_than_5 = mx_concat[(mx_concat > 5)]

In [149]:
mx_bigger_than_5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [150]:
mx_slicing = mx_concat[0]

In [151]:
mx_slicing

array([1, 2, 3, 4, 5, 6])

In [152]:
mx_concat

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [153]:
mx_concat[:2]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [154]:
mx_slicing = mx_concat.copy()

In [155]:
mx_slicing[0,0:3]

array([1, 2, 3])

In [156]:
mx_concat

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [157]:
mx_slicing[0]

array([1, 2, 3, 4, 5, 6])

In [158]:
mx_slicing[:,0]

array([ 1,  7, 13, 19])